version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
        - apt-get install -y maven
  build:
    commands:
        - mvn clean package
        - mkdir output
        - cp target/*.war output/books.war
artifacts:
  files:
        - 'output/*.war'
        - appspec.yml
        - scripts/*
